### ISSUE TITLE
Custom noteskins in settings dont work

### ISSUE THREAD

**Issue by GhostL650** [beihu235/Psych-Engine-0.71h-Android#2]
### Describe your bug here.

I want to add custom noteskin to the folder .PsychEngine/mods/images/noteSkins but dosent work
I tried edit the list.txt file but dosent work too

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by beihu235** [comment]
yes it really not work,l will fix it about 2days

**Comment by GhostL650** [comment]
> yes it really not work,l will fix it about 2days

Ok

**Comment by GhostL650** [comment]
Thank you fo fixing it
