### ISSUE TITLE
The new version crashes after install

### ISSUE THREAD

**Issue by GhostL650** [beihu235/Psych-Engine-0.71h-Android#8]
### Describe your bug here.

I downloaded the new version 1.1.0 and after i opened it the game crash

### Command Prompt/Terminal logs (if existing)

```bash
Nothing
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by GhostL650** [comment]
https://github.com/beihu235/Psych-Engine-0.71h-android/assets/93405967/914cc4cb-3a27-4e4c-9d19-69e1c9bb025e

**Comment by beihu235** [comment]
You may have the file access turned off

**Comment by beihu235** [comment]
or your version is debug version,at least now it cant use

**Comment by GhostL650** [comment]
Thanks
